nightly.yml: Remove step to install Android SDK manually
This has since been added to the list of available software: https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts

See actions/starter-workflows#58 for more info

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -16,34 +16,34 @@ jobs:
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
-    - name: Install Android SDK Platform 29 and Build-Tools 29.0.2
-      run: |
-        cd
-        echo "Current working directory:"
-        pwd
-        wget -nv https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
-        unzip -q sdk-tools-linux-4333796.zip
-        rm sdk-tools-linux-4333796.zip
-        mkdir android-sdk
-        mv tools android-sdk/tools
+#     - name: Install Android SDK Platform 29 and Build-Tools 29.0.2
+#       run: |
+#         cd
+#         echo "Current working directory:"
+#         pwd
+#         wget -nv https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
+#         unzip -q sdk-tools-linux-4333796.zip
+#         rm sdk-tools-linux-4333796.zip
+#         mkdir android-sdk
+#         mv tools android-sdk/tools
 
-        echo "Available Platform Tools:"
-        ls -hAFl --color=auto ~/android-sdk/tools/bin
-        echo "Adding Android SDK to PATH..."
-        echo '# Export the Android SDK path' >> ~/.profile
-        echo 'export ANDROID_HOME=$HOME/android-sdk' >> ~/.profile
-        echo 'PATH=$PATH:$ANDROID_HOME/tools/bin' >> ~/.profile
-        echo -e '\n# Fixes sdkmanager error with java versions higher than java 8' >> ~/.profile
-        echo '# export JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"' >> ~/.profile
-        echo "Result of cat ~/.profile:"
-        cat ~/.profile
-        source ~/.profile
-        echo "Current PATH:"
-        echo $PATH
-        echo "Accepting licenses..."
-        yes | sdkmanager --licenses
-        echo "Installing Android SDK Platform 29 and Build-Tools 29.0.2 with sdkmanager..."
-        sdkmanager "build-tools;29.0.2" "platforms;android-29" | grep -v = || true
+#         echo "Available Platform Tools:"
+#         ls -hAFl --color=auto ~/android-sdk/tools/bin
+#         echo "Adding Android SDK to PATH..."
+#         echo '# Export the Android SDK path' >> ~/.profile
+#         echo 'export ANDROID_HOME=$HOME/android-sdk' >> ~/.profile
+#         echo 'PATH=$PATH:$ANDROID_HOME/tools/bin' >> ~/.profile
+#         echo -e '\n# Fixes sdkmanager error with java versions higher than java 8' >> ~/.profile
+#         echo '# export JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"' >> ~/.profile
+#         echo "Result of cat ~/.profile:"
+#         cat ~/.profile
+#         source ~/.profile
+#         echo "Current PATH:"
+#         echo $PATH
+#         echo "Accepting licenses..."
+#         yes | sdkmanager --licenses
+#         echo "Installing Android SDK Platform 29 and Build-Tools 29.0.2 with sdkmanager..."
+#         sdkmanager "build-tools;29.0.2" "platforms;android-29" | grep -v = || true
     - name: Install GPG2
       run: sudo apt-get install gnupg2
     - name: Install Homebrew
